name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.6.6]
        jekyll: [3.0, 4.0]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
      env:
        JEKYLL_VERSION: ${{ matrix.jekyll }}
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake spec
